#!/usr/bin/env bash

# `pkgup`
# upgrade all installed packages into a new directory in pkgbld
# using method nubmer 12 Alternative LOCALBASE and PKG_DBDIR
# http://wiki.netbsd.org/pkgsrc/how_to_upgrade_packages/#index14h2

set -eu

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" # http://stackoverflow.com/questions/59895
. "$DIR/setenv.sh"		# is this actually needed if we aren't bootstrapping?

# get a list of installed packages
packages=$(pkg_info -a -B | grep PKGPATH)
packages=${packages//PKGPATH=/}
echo "re-installing these packages into a new LOCALBASE"
echo $packages

# update the pkgsrc directory via git commands

cd $HOME/pkgsrc

# check if git needs updating
# http://stackoverflow.com/a/16920556/1763984
if [ "`git log --pretty=%H ...trunk^ | head -n 1`" = "`git ls-remote origin -h trunk |cut -f1`" ] ; then
    echo "Already up-to-date."
    exit
fi
# pull in the latest changes from github
git pull

# re-bootstrap to a new pkgbld/<gitchksum>
cd bootstrap
rm -rf work
tag=`git rev-parse --short --verify HEAD`
./bootstrap --prefix "$HOME/pkgbld/$tag" --pkgdbdir "$HOME/pkgbld/$tag/var/db/pkg" --unprivileged

# hack the path to point to the new directory
export PATH=${PATH//$HOME\/pkg/$HOME\/pkgbld\/$tag}

# install all the packages into the new directory
$DIR/pmake $packages

echo "change the symbolic link to point to $TAG"


# Copyright © 2013, Regents of the University of California
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without 
# modification, are permitted provided that the following conditions are met:
# 
# - Redistributions of source code must retain the above copyright notice, 
#   this list of conditions and the following disclaimer.
# - Redistributions in binary form must reproduce the above copyright notice, 
#   this list of conditions and the following disclaimer in the documentation 
#   and/or other materials provided with the distribution.
# - Neither the name of the University of California nor the names of its
#   contributors may be used to endorse or promote products derived from this 
#   software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE 
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
# POSSIBILITY OF SUCH DAMAGE.
