#!/usr/bin/env bash

# minimum certs required to start https

mkdir -p $HOME/certs

# create a test certificate
openssl req -new -x509 -nodes \
        -out $HOME/certs/test.crt \
        -keyout $HOME/certs/test.key \
        -batch
