#!/usr/bin/env bash

# pkgsrc can compile www/shibboleth-sp; but the version it compiles is configured to run
# as root -- so pkgsrc is used to get all the dependencies; and then it is recompiled
# again setting a prefix

set -eu

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" # http://stackoverflow.com/questions/59895
. "$DIR/setenv.sh"

cd $DIR

if [ ! -e "$HOME/pkgsrc/distfiles/shibboleth-sp-2.4.3.tar.gz" ]; then
  ./pmake www/shibboleth-sp
  pkg_delete shibboleth-sp-2.4.3nb2
fi

if [ ! -e "$HOME/pkgsrc/distfiles/shibboleth-sp-2.4.3.tar.gz" ]; then
  echo "must have upgraded pkgsrc..., now this scripts needs updating"
  exit 1
fi

shibdir="$HOME/servers/shibboleth"
mkdir -p $shibdir
cd $shibdir

tar zxf "$HOME/pkgsrc/distfiles/shibboleth-sp-2.4.3.tar.gz"
cd shibboleth-2.4.3
./configure --prefix=$shibdir --with-xmltooling=$HOME/pkg
make install

echo "before you run apache; set these
  export SHIBSP_PREFIX=$HOME/servers/shibboleth
  export LD_LIBRARY_PATH=$HOME/servers/shibboleth/lib
  UseCanonicalName On
  ServerName app.example.org:443
  also Include a copy of $HOME/servers/shibboleth/etc/shibboleth/apache22.config 
"

# Copyright © 2013, Regents of the University of California
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without 
# modification, are permitted provided that the following conditions are met:
# 
# - Redistributions of source code must retain the above copyright notice, 
#   this list of conditions and the following disclaimer.
# - Redistributions in binary form must reproduce the above copyright notice, 
#   this list of conditions and the following disclaimer in the documentation 
#   and/or other materials provided with the distribution.
# - Neither the name of the University of California nor the names of its
#   contributors may be used to endorse or promote products derived from this 
#   software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE 
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
# POSSIBILITY OF SUCH DAMAGE.
