#!/bin/sh
### BEGIN INIT INFO
# Provides: nuxeo
# Required-Start: $local_fs $network $remote_fs
# Should-Start: ypbind nscd ntpd xntpd
# Required-Stop: $local_fs $network $remote_fs
# Default-Start: 3 5
# Default-Stop: 0 1 2 6
# Description: This script starts/stops nuxeomonit services
### END INIT INFO
#
# chkconfig: 345 99 01
# description: Start and stop DSC services

. /etc/rc.d/init.d/functions

ROLE=nuxeo

case "$1" in
  start)
      /bin/su - $ROLE -c "/home/nuxeo/nuxeo/bin/nuxeoctl startbg"
      touch /var/lock/subsys/nuxeo
      ;;
  stop)
      /bin/su - $ROLE -c "/home/nuxeo/nuxeo/bin/nuxeoctl stop"
      rm -f /var/lock/subsys/nuxeo
      ;;
  *)
      echo "dsc start/stop script"
esac
