#!/bin/sh
### BEGIN INIT INFO
# Provides: nuxeomonit
# Required-Start: $local_fs $network $remote_fs
# Should-Start: ypbind nscd ntpd xntpd
# Required-Stop: $local_fs $network $remote_fs
# Default-Start: 3 5
# Default-Stop: 0 1 2 6
# Description: This script starts/stops nuxeomonit services
### END INIT INFO
#
# chkconfig: 345 99 01
# description: Start and stop DSC services

. /etc/rc.d/init.d/functions

case "$1" in
  start)
      /bin/su - dsc -c "/usr/bin/monit -c ~/.monitrc"
      /bin/su - dsc -c "/usr/bin/monit -c ~/.monitrc start all"
      touch /var/lock/subsys/nuxeomonit
      ;;
  stop)
      /bin/su - dsc -c "/usr/bin/monit -c ~/.monitrc stop all"
      /bin/su - dsc -c "/usr/bin/monit -c ~/.monitrc quit"
      rm -f /var/lock/subsys/nuxeomonit
      ;;
  *)
      echo "dsc start/stop script"
esac
