# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
if [ -f ~/appstrap/setenv.sh ]; then
	. ~/appstrap/setenv.sh
fi

export CATALINA_BASE=~/servers/tomcat
