#!/usr/bin/env bash
set -eu
# http://mmonit.com/monit/download/
set -x
cd
mkdir -p src
cd src
file="monit-5.5.1-linux-x64.tar.gz"
vers="5.5.1"
binary="http://mmonit.com/monit/dist/binary/$vers/$file"
sha256="2075423c8109eff9c92d8bde95edff6fb36cb73844b6e02dee5f6bf8dbaa595f"

wget "$binary"
check=$(sha256sum $file)
check=$(echo ${check/ */}) # strip off filename
if ! [[ "$check" = "$sha256" ]]; then
  echo "checksum mismatch"
  exit 1
fi

tar zxf "$file"
# overwrite the pkgsrc versions if they exist
cp -f monit-$vers/bin/monit ~/pkg/bin/monit
cp -f monit-$vers/man/man1/monit.1 ~/pkg/man/man1/monit.1 
