#!/usr/bin/env bash
set -eu
# http://mmonit.com/monit/download/
set -x
cd
mkdir -p src
cd src
if [[ -e monit-5.8-linux-x64.tar.gz ]];then 
  echo "been done"
  exit 0
fi
file="monit-5.8-linux-x64.tar.gz"
vers="5.8"
binary="http://mmonit.com/monit/dist/binary/$vers/$file"
sha256='a324d67a253f6ab6cf2de34d63cc8e0e7352287ae59e5c4afcb55d059230e388'

wget "$binary"
check=$(sha256sum $file)
check=$(echo ${check/ */}) # strip off filename
if ! [[ "$check" == "$sha256" ]]; then
  echo "checksum mismatch"
  exit 1
fi

tar zxf "$file"
# overwrite the pkgsrc versions if they exist
cp -f monit-$vers/bin/monit ~/pkg/bin/monit
cp -f monit-$vers/man/man1/monit.1 ~/pkg/man/man1/monit.1 
