#!/usr/bin/env bash

if [ -z "$DEBUG" ]; then 
  set -x
fi

set -o pipefail  # trace ERR through pipes
set -o errtrace  # trace ERR through 'time command' and other functions
set -o nounset   ## set -u : exit the script if you try to use an uninitialised variable
set -o errexit   ## set -e : exit the script if any statement returns a non-true return value

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" # http://stackoverflow.com/questions/59895
cd $DIR

../shib_it
export ACCEPTABLE_LICENSES=lame-license ../pmake multimedia/ffmpeg
../pmake graphics/ImageMagick
../pmake print/poppler-utils

# install openoffice "by hand"

# install nuxeo; has some steps that really must actually be done by hand :(
