#!/usr/bin/env bash

if [[ -n "$DEBUG" ]]; then 
  set -x
fi

set -o pipefail  # trace ERR through pipes
set -o errtrace  # trace ERR through 'time command' and other functions
set -o nounset   ## set -u : exit the script if you try to use an uninitialised variable
set -o errexit   ## set -e : exit the script if any statement returns a non-true return value

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" # http://stackoverflow.com/questions/59895
cd $DIR

. stack_run.sh  # gives us `stack_run_batch`

echo "===============================GET JAVA NEXT"
export PKG_JVM_DEFAULT=sun-jdk7
export CPP='/usr/bin/cpp'
export CXX='/usr/bin/gcc'
#export PKG_OPTIONS.sun-jre7=sun-jre-jce
ACCEPTABLE_LICENSES=oracle-binary-code-license ../pmake lang/sun-jre7
echo "================================PMAKE solr.pkgsrc.txt"
ACCEPTABLE_LICENSES=oracle-binary-code-license stack_run_batch "../pmake" solr.pkgsrc.txt
