#!/usr/bin/env bash

if [ -z "$DEBUG" ]; then 
  set -x
fi
set -eu

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" # http://stackoverflow.com/questions/59895
cd $DIR

. stack_run.sh

# unset build-dsc-solaris10 environment
unset CFLAGS
unset CPPFLAGS
unset LDFLAGS
unset LD_LIBRARY_PATH
unset LD_RUN_PATH
unset PERL5LIB
unset PREFIX
# restore default path on SUSE
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/X11R6/bin:/usr/games:/usr/lib/mit/bin:/usr/lib/mit/sbin

../shib_it
stack_run_batch "../pmake" dsc.pkgsrc.txt
. ../setenv.sh
stack_run_batch  "pip install" dsc.pip.txt
stack_run_batch "cpanm" dsc.cpanm.txt
