#!/usr/bin/env bash

if [[ -n "$DEBUG" ]]; then 
  set -x
fi

set -o pipefail  # trace ERR through pipes
set -o errtrace  # trace ERR through 'time command' and other functions
set -o nounset   ## set -u : exit the script if you try to use an uninitialised variable
set -o errexit   ## set -e : exit the script if any statement returns a non-true return value

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" # http://stackoverflow.com/questions/59895
cd $DIR

. stack_run.sh

# unset build-dsc-solaris10 environment
unset CFLAGS
unset CPPFLAGS
unset LDFLAGS
unset LD_LIBRARY_PATH
unset LD_RUN_PATH
unset PERL5LIB
unset PREFIX
# restore default path on SUSE
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/X11R6/bin:/usr/games:/usr/lib/mit/bin:/usr/lib/mit/sbin

stack_run_batch "../pmake" dsc.pkgsrc.txt
# install openquicktime "by hand" (needs patch?)
. ../setenv.sh
which pip
stack_run_batch  "pip install" dsc.pip.txt
which cpanm
stack_run_batch "cpanm" dsc.cpanm.txt
# install File::List "by hand"
