#!/usr/bin/env bash
export DEBUG=1
if [[ -n ${DEBUG-} ]]; then 
  set -x
fi

set -o pipefail  # trace ERR through pipes
set -o errtrace  # trace ERR through 'time command' and other functions
set -o nounset   ## set -u : exit the script if you try to use an uninitialised variable
set -o errexit   ## set -e : exit the script if any statement returns a non-true return value

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" # http://stackoverflow.com/questions/59895
cd $DIR

# test ssl certs in ~/certs
../roll_test_certs

# set up virtualenv and activate it
virtualenv-2.7 ~/python
set +u
source ~/python/bin/activate
set -u

# python libraries
pip install \
  appdirs \
  daemonocle \
  lxml \
  mysql \
  shove \
  six
pip install https://github.com/ucldc/staller/archive/master.zip
pip install -r ../ansible/requirements.txt --use-mirrors

# check for shibboleth and build if needed
if [[ ! -x ~/servers/shibboleth/sbin/shibd ]]
  then
    shib_it -p ${HOME}/servers/shibboleth \
      --boost /usr/include/boost141 \
      --curl /usr \
      --openssl /usr \
      --apxs /usr/bin/apxs 
fi


# okay, now we should have a good stack set up, let's install and configure the app!
cd ../ansible

ansible-playbook -i host_inventory registry-playbook.yml
pip install -r ~/code/avram/requirements.txt
cd
ln -f -s appstrap/bashrc/role-account .bashrc
mkdir -p ~/users
touch ~/users/api_key.conf
