#!/usr/bin/env bash
export DEBUG=1
if [[ -n ${DEBUG-} ]]; then 
  set -x
fi

set -o pipefail  # trace ERR through pipes
set -o errtrace  # trace ERR through 'time command' and other functions
set -o nounset   ## set -u : exit the script if you try to use an uninitialised variable
set -o errexit   ## set -e : exit the script if any statement returns a non-true return value

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" # http://stackoverflow.com/questions/59895
cd $DIR

./registry.yum.sh

# test ssl certs in ~/certs
../roll_test_certs

pip3 install virtualenv

# set up virtualenv and activate it
virtualenv-3 ~/python --python=/usr/bin/python3
set +u
source ~/python/bin/activate
set -u

# python libraries
pip install -r registry.pip.txt
pip install -r ../ansible/requirements.txt

# check for shibboleth and build if needed
if [[ ! -x /usr/sbin/shibd ]]
  then
    curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -d "platform=CentOS_7" https://shibboleth.net/cgi-bin/sp_repo.cgi -o shib_centos7.repo
    sudo yum-config-manager --add-repo shib_centos7.repo
    rm shib_centos7.repo
    sudo yum -y install shibboleth

fi

# okay, now we should have a good stack set up, let's install and configure the app!
cd ../ansible

ansible-playbook -i host_inventory registry-playbook.yml
pip install -r ~/code/avram/requirements.txt
cd
ln -f -s appstrap/bashrc/role-account .bashrc
mkdir -p ~/users
touch ~/users/api_key.conf
