#!/usr/bin/env bash
export DEBUG=1
if [[ -n ${DEBUG-} ]]; then 
  set -x
fi

set -o pipefail  # trace ERR through pipes
set -o errtrace  # trace ERR through 'time command' and other functions
set -o nounset   ## set -u : exit the script if you try to use an uninitialised variable
set -o errexit   ## set -e : exit the script if any statement returns a non-true return value

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" # http://stackoverflow.com/questions/59895
cd $DIR

pip install lxml
pip install https://github.com/ucldc/staller/archive/master.zip
pip install six
pip install https://github.com/tingletech/fixity_checker/archive/master.tar.gz
shib_it -p ${HOME}/servers/shibboleth \
  --boost /usr/include/boost141 --curl /usr --openssl /usr --apxs /usr/bin/apxs 

../roll_test_certs

exit 0

# okay, now we should have a good stack set up, let's install and configure the app!
cd ../ansible
if [[ ! -d bin ]]; then
  ./init.sh
fi
set +u
. bin/activate
set -u
ansible-playbook -i host_inventory nuxeo-playbook.yml
cd
ln -f -s appstrap/bashrc/role-account .bashrc
