#!/usr/bin/env bash

if [[ -x /usr/bin/cloud-init ]]
  then
  # running in Amazon
    public_hostname=$(curl http://169.254.169.254/latest/meta-data/public-hostname --silent)
    if [[ -z $public_hostname ]]
      then
      # fallback, VPC's don't have public hostname DNS by default
        host=$(host $(curl http://169.254.169.254/latest/meta-data/public-ipv4 --silent))
        host=${host##*domain name pointer }
        myhostname=${host::1,${#host}-1}
      else 
        myhostname="$public_hostname"
    fi

  else
  # running in Kaiser
    hostname=$(hostname)

    case "$hostname" in
      'registry-dev' )
        myhostname='registry-dev.cdlib.org' ;;
      'registry-stg' )
        myhostname='registry-stg.cdlib.org' ;;
      'cdl-registry-p01' )
        myhostname='registry.cdlib.org' ;;
      'nuxeo-dev' )
        myhostname='nuxeo-dev.cdlib.org' ;;
      'nuxeo-stg' )
        myhostname='nuxeo-stg.cdlib.org' ;;
      'cdl-nuxeo-p01' )
        myhostname='nuxeo.cdlib.org' ;;
      'publishing-stg' )
        myhostname='licensed-stg.cdlib.org' ;;
      'cdl-ucpec-p01' )
        myhostname='licensed.cdlib.org' ;;
      * )
        myhostname="$hostname" ;;
    esac
fi

echo "$myhostname"
