---
-   hosts: ec2
    tasks:
################################################################################
################################################################################
################################################################################
# The yum steps should already be done by user data to ec2
# Doesn't hurt to run again and doesn't take much time.
    - name: update host
      sudo: yes
      shell: yum -y update

############################################################################
#   pkgsrc requirements
    - name: yum ncurses
      sudo: yes
      shell: yum -y install ncurses-devel ncurses
    - name: yum zlib
      sudo: yes
      shell: yum -y install zlib-devel zlib
    - name: yum openssl
      sudo: yes
      shell: yum -y install openssl-devel openssl
    - name: yum gcc
      sudo: yes
      shell: yum -y install gcc
    - name: yum gcc c++
      sudo: yes
      shell: yum -y install gcc-c++
    - name: yum libstdc++-devel
      sudo: yes
      shell: yum -y install libstdc++-devel
#   pkgsrc requirements end
################################################################################

    - name: yum git
      sudo: yes
      shell: yum -y install git
################################################################################
################################################################################
################################################################################

    - name: clone_appstrap
      git: repo=https://github.com/mredar/appstrap.git dest=/home/ec2-user/appstrap
    - name: add_bash
      shell: cat $HOME/appstrap/bashrc_add >> $HOME/.bashrc
    - name: pkgsrc_make
      shell: $HOME/appstrap/pmake
    - name: check_appstrap
      shell: . $HOME/appstrap/setenv.sh
    - name: get_jre_dist
      command: aws s3 get-object --bucket dsc-internal-java --key java7/jre-7u21-linux-x64.tar.gz pkgsrc/distfiles/jre-7u21-linux-x64.tar.gz
    - name: run_appstrap_stack
      shell: $HOME/appstrap/stacks/stack_solr
